version: 2
updates:
  # Configuration for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  # Configuration for Bundler
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
