language: ruby

rvm:
 - 3.0.0

services:
  - postgresql

install:
  - bundle install

script:
  - RAILS_ENV=test bundle exec rake db:migrate:reset
  - bundle exec rspec
  - bundle exec rubocop
  - bundle exec rails_best_practices
